### ISSUE TITLE
《Weibo_Android_SDK开发手册》中的错别字

### ISSUE THREAD

**Issue by flypen** [mobileresearch/weibo_android_sdk#12]
《Weibo_Android_SDK开发手册》中的错别字：
PDF文档第1页：用户登录完成后最后悔跳转此地址... “最后悔”应该为“最后会”。
PDF文档第2页：在使用 SDK 时,配置授权毁掉也是必不可少的...“毁掉也是”应该为“回调也是”。
唉，都是拼音输入法惹出来的事儿……

**Comment by mobileresearch** [comment]
@flypen 感谢提醒。虽然看起来这是小问题，但是反映了一个专业素质和水平。再次感谢，欢迎体验V2.4.0版本的SDK，期望再次能收到您宝贵的意见。
