### ISSUE TITLE
例子与官方api流程不一致

### ISSUE THREAD

**Issue by fatmind** [mobileresearch/weibo_android_sdk#13]
1.官方api流程
a、OAuth2/authorize，get获取code
b、Oauth2/access_token，post方式获取token

2.官方例子
a、OAuth2/authorize，设置 response_type=toke，get方式一次性取到

3.google到的解释
http://www.cocoachina.com/bbs/simple/?t94142.html

既然是官方的文档，希望可以遵循当前最新的规则，不然会给开发者带来迷惑。谢谢

**Comment by mobileresearch** [comment]
@fatmind 感谢您提供的宝贵意见，该问题已做修正，欢迎体验V2.4.0的代码及文档，再次期望您能提出宝贵的意见。
