### ISSUE TITLE
文档里面提到有三个jar, 怎么只有一个直接可以下载？

### ISSUE THREAD

**Issue by Teaonly** [mobileresearch/weibo_android_sdk#15]
在根目录下直接的***.sso.jar是否是独立完整的.jar可以直接使用？越看文档越糊涂！

**Comment by Teaonly** [comment]
测试下来，只需要 weibo.sdk.android.sso.jar 和 android-support-v4.jar 两个jar文件就足够了。

建议更新文档，超级看不懂

**Comment by mobileresearch** [comment]
@Teaonly 感谢您提供的宝贵意见，该问题已做修正，欢迎体验V2.4.0的代码及文档，再次期望您能提出宝贵的意见。
