### ISSUE TITLE
新版DEMO和我自己测试的APP中通过SSO授权后，又会弹出网页授权，还得手动输入一次～

### ISSUE THREAD

**Issue by cstdr** [mobileresearch/weibo_android_sdk#22]
新版DEMO和我自己测试的APP中通过SSO授权后，又会弹出网页授权，还得手动输入一次～

已经按要求在网上和代码中都添加了OAuth2.0客户端默认回调页：https://api.weibo.com/oauth2/default.html

使用的方法和DEMO中一致，不知道是哪里还需要修改？

**Comment by mobileresearch** [comment]
请认真看说明文档，还有需要注册你应用的appkey，包名和签名。

**Comment by DreamXWH** [comment]
我也一样。还得输入。而且onComplete返回都没有access_token和expires_in。 appkey，包名和签名 都填写好了。。。为什么啊？

**Comment by cstdr** [comment]
请问“包名和签名”在哪里填写，工作一天眼睛有点花了，看了几遍官网和文档，请给点提示吧～
![image](https://f.cloud.github.com/assets/2403716/547911/f223e74a-c2d4-11e2-89e1-3d68628ce8df.png)

**Comment by cstdr** [comment]
我发现文档、demo和jar包已经更新了～
我使用SSO登录正常，返回的不再是Code，而是Token了～

看来要时刻来github上看看才行～问题解决～
