### ISSUE TITLE
无网络时调用anthorize crash

### ISSUE THREAD

**Issue by xiaohui8801** [mobileresearch/weibo_android_sdk#23]
网络关闭后，调用anthorize crash
而sdk内提供的Demo则不会crash提示
<string name="checkinternet">无法联系网络，请检查网络配置</string>
这个字符串的id写在sdk内了吧

**Comment by cstdr** [comment]
请问你使用SSO授权，是否还需要重新输入一次帐号和密码？
我这边一直是这样，使用DEMO测试也是这样，回调地址我用的是官方的默认地址：
https://api.weibo.com/oauth2/default.html

希望能得到一些指点，谢谢啦～

**Comment by mobileresearch** [comment]
请认真看说明文档，还有需要注册你应用的appkey，包名和签名。

**Comment by mobileresearch** [comment]
@xiaohui8801 @cstdr 该问题已被修正，欢迎使用V2.4.0
