### ISSUE TITLE
新版DEMOSSO授权无法获取access_token

### ISSUE THREAD

**Issue by saleemshenlin** [mobileresearch/weibo_android_sdk#24]
本人是新手。
使用新版DEMO的SSO时，发生crash。
在
class AuthDialogListener implements WeiboAuthListener下的public void onComplete(Bundle values) 中
能够获取code，但是无法获取access_token
。

**Comment by mobileresearch** [comment]
请认真看说明文档，还有需要注册你应用的appkey，包名和签名。

**Comment by saleemshenlin** [comment]
![image](https://f.cloud.github.com/assets/3690320/548148/35636d08-c2dc-11e2-97a3-3c5a614f5f10.png)
![image](https://f.cloud.github.com/assets/3690320/548152/43348d22-c2dc-11e2-9754-5186581af4d5.png)
我是在AVD上试了，好像没有用啊，要真机？？
不好意思，大神见谅，我是个新手！
谢谢！

**Comment by saleemshenlin** [comment]
更新了SSO接口！

**Comment by yuduozhou** [comment]
public void onComplete(Bundle values) {
  for (String key : values.keySet()) {
    Log.i(TAG, "values:key = " + key + " value = "  + values.getString(key));
  }
。。。

SSO登陆方式返回结果中只有
values:key = code value = {access code}

请问如何才能返回token？

**Comment by lightlz** [comment]
在api里面有关于如何获取到token的方法，是要用post|get，发送code，自己写http，能够返回token的值。sdk中直接获得token的方法已经被新浪弄掉了。

------------------ 原始邮件 ------------------
发件人: "Yuduo Zhou"; 
发送时间: 2013年8月13日(星期二) 上午7:24
收件人: "mobileresearch/weibo_android_sdk"; 
主题: Re: [weibo_android_sdk] 新版DEMOSSO授权无法获取access_token (#24)

public void onComplete(Bundle values) {
   for (String key : values.keySet()) {
     Log.i(TAG, "values:key = " + key + " value = "  + values.getString(key));
   }
 。。。

SSO登陆方式返回结果中只有
 values:key = code value = {access code}

请问如何才能返回token？

&mdash;

**Comment by yuduozhou** [comment]
谢谢！已经搞定了

On Mon, Aug 12, 2013 at 8:01 PM, lightlz notifications@github.com wrote:

> 在api里面有关于如何获取到token的方法，是要用post|get，发送code，自己写http，能够返回token的值。sdk中直接获得token的方法已经被新浪弄掉了。
> 
> ------------------ 原始邮件 ------------------
> 发件人: "Yuduo Zhou";
> 发送时间: 2013年8月13日(星期二) 上午7:24
> 收件人: "mobileresearch/weibo_android_sdk";
> 主题: Re: [weibo_android_sdk] 新版DEMOSSO授权无法获取access_token (#24)
> 
> public void onComplete(Bundle values) {
> for (String key : values.keySet()) {
> Log.i(TAG, "values:key = " + key + " value = " + values.getString(key));
> }
> 。。。
> 
> SSO登陆方式返回结果中只有
> values:key = code value = {access code}
> 
> 请问如何才能返回token？
> 
> &mdash;
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mobileresearch/weibo_android_sdk/issues/24#issuecomment-22540524
> .

## 

Yuduo Zhou
School of Informatics and Computing
Indiana University Bloomington
