### ISSUE TITLE
唉，这个SDK一堆问题，怎么签名？横屏显示不全？授权后直接CRASH？

### ISSUE THREAD

**Issue by choujimmy** [mobileresearch/weibo_android_sdk#25]
1：文档里面写建立WEIBO实例后注册应用程序包名和签名，在哪里注册？没有任何接口函数，网站管理控制台也没有这些项目
2：开始anthorize后弹出认证页面在横屏时显示不全（800*480分辨率）
3：授权成功后仅返回CODE，不返回ACCESS_TOKEN，而且屏幕上还是继续LOADING，大约10秒后直接将应用程序CRASH
4：改用SSOHANDLER方式，出现绿色的登录页面后又无限制的循环进入红色的页面方式的登录页面

谁能帮帮我？

**Comment by bladeFury** [comment]
同 **1** 和 **4** 
这样的SDK放出来叫我们怎么用啊

**Comment by cstdr** [comment]
我发现文档、demo和jar包已经更新了，你可以再试试～
我使用SSO登录正常，返回的不再是Code，而是Token了～

看来要时刻来github上看看才行～

**Comment by bladeFury** [comment]
嗯，不过之前那个版本貌似是有SSO发布微博的接口的，跟微信很像
这版就去掉了，发微博只能走oauth了

**Comment by cstdr** [comment]
我写了一个DEMO，能够正常绑定，发微博，如果需要可以去看看源码，里面有注释说明：
https://github.com/cstdr/WeiboSDKDemo

**Comment by daimajia** [comment]
坑...

**Comment by mobileresearch** [comment]
@choujimmy @bladeFury @daimajia 感谢您提供的宝贵意见，该问题已做修正，欢迎体验V2.4.0，您可以看看V2.4.0的文档以及FAQ，上面的问题都有对应的答案，谢谢。再次期望您能提出宝贵的意见。
