### ISSUE TITLE
WeiboAuthListener onComplete

### ISSUE THREAD

**Issue by xiaohui8801** [mobileresearch/weibo_android_sdk#26]
验证一次，onComplete响应两次，而且获取code后还有一个loading的Dialog一直显示，要敲击下屏幕才会消失，请问是怎么回事啊？

**Comment by cstdr** [comment]
你可以更新下最新的jar包，我今天刚用，可以直接获取到token，没有code返回了～

**Comment by cstdr** [comment]
我写了一个DEMO，能够正常绑定，发微博，如果需要可以去看看源码，里面有注释说明：
https://github.com/cstdr/WeiboSDKDemo

**Comment by mobileresearch** [comment]
@xiaohui8801 @cstdr 感谢您提供的宝贵意见，该问题已做修正，欢迎体验V2.4.0的代码及文档，再次期望您能提出宝贵的意见。
