### ISSUE TITLE
SDK2.0里面Weibo.URL_OAUTH2_ACCESS_AUTHORIZE貌似不正确

### ISSUE THREAD

**Issue by metax** [mobileresearch/weibo_android_sdk#3]
程序中写的是https://open.weibo.cn/oauth2/authorize，改成https://api.weibo.com/oauth2/authorize后可用。

**Comment by mobileresearch** [comment]
@metax 感谢您提供的宝贵意见，该问题已做修正，欢迎体验V2.4.0的代码及文档，再次期望您能提出宝贵的意见。
