### ISSUE TITLE
你好，demo中的sso登陆无法运行成功

### ISSUE THREAD

**Issue by yuduozhou** [mobileresearch/weibo_android_sdk#37]
新浪微博app已登录。
demo中选登陆sso，loading之后直接出现到达授权界面，选择允许授权。之后出现短暂的loading，之后直接跳回到需要输入用户名和密码的登陆界面。
如此无限循环。

我直接运行的官方demo程序，只修改了app_key和redirect_url。此外没有任何修改，请问可能的原因有哪些？

**Comment by achellies** [comment]
需要使用demo中提供的debug.keystore

**Comment by Salijing** [comment]
不会啊，你是否装有客户端？

在 2013-08-13 16:59:03，achellies notifications@github.com 写道：

需要使用demo中提供的debug.keystore

**Comment by mobileresearch** [comment]
@yuduozhou 请替换 debug.keystore，详情请见：[常见问题FAQ](https://github.com/mobileresearch/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md) 或 [微博Android平台SDK文档V2.4.0.pdf](https://github.com/mobileresearch/weibo_android_sdk/blob/master/%E5%BE%AE%E5%8D%9AAndroid%E5%B9%B3%E5%8F%B0SDK%E6%96%87%E6%A1%A3V2.4.0.pdf)
