### ISSUE TITLE
现在的版本在授权的时候怎么还只返回code ?

### ISSUE THREAD

**Issue by feezoner** [mobileresearch/weibo_android_sdk#40]

**Comment by mobileresearch** [comment]
@feezoner 如果您注册的应用程序的包名和签名不正确，就会导致该问题。详情请见：[常见问题FAQ](https://github.com/mobileresearch/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md)
