### ISSUE TITLE
v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权

### ISSUE THREAD

**Issue by heiyl** [mobileresearch/weibo_android_sdk#41]
v2.1版SDK还是重复初相授权页面，两次授权，第一次SSO流程选择帐号-->允许-->再次弹出webview页面要求输入帐号密码-->授权登录后报错，说是类型转换异常，（long型数据）

**Comment by woyaowenzi** [comment]
我怀疑你的应用没有注册应用程序的包名和签名。

**Comment by cstdr** [comment]
应该是这个原因，我用公司注册过的签名就正常授权~
我GitHub有自己写的Demo，如果需要可以参考下~

------------------ 原始邮件 ------------------
发件人: "woyaowenzi";notifications@github.com;
发送时间: 2013年9月12日(星期四) 中午11:09
收件人: "mobileresearch/weibo_android_sdk"weibo_android_sdk@noreply.github.com; 

主题: Re: [weibo_android_sdk] v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权 (#41)

我怀疑你的应用没有注册应用程序的包名和签名。

**Comment by heiyl** [comment]
怎么注册包名和签名？在开房平台上应用信息中根据要求写过！

---

From: 丁冉
Sent: 周四, 9月 12, 2013 11:08 上午
To: mobileresearch/weibo_android_sdk weibo_android_sdk@noreply.github.com
CC: 黑玉龙 heiyl@chanjet.com
Subject: Re: [weibo_android_sdk] v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权 (#41)

应该是这个原因，我用公司注册过的签名就正常授权~
我GitHub有自己写的Demo，如果需要可以参考下~

------------------ 原始邮件 ------------------
发件人: "woyaowenzi";notifications@github.com;
发送时间: 2013年9月12日(星期四) 中午11:09
收件人: "mobileresearch/weibo_android_sdk"weibo_android_sdk@noreply.github.com;

主题: Re: [weibo_android_sdk] v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权 (#41)

我怀疑你的应用没有注册应用程序的包名和签名。

**Comment by cstdr** [comment]
看看新浪官方文档吧，有具体步骤的~

------------------ 原始邮件 ------------------
发件人: "heiyl";notifications@github.com;
发送时间: 2013年9月12日(星期四) 中午11:23
收件人: "mobileresearch/weibo_android_sdk"weibo_android_sdk@noreply.github.com; 
抄送: "丁冉"cstdingran@gmail.com; 
主题: Re: [weibo_android_sdk] v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权 (#41)

怎么注册包名和签名？在开房平台上应用信息中根据要求写过！ 

---

 From: 丁冉 
 Sent: 周四, 9月 12, 2013 11:08 上午 
 To: mobileresearch/weibo_android_sdk weibo_android_sdk@noreply.github.com 
 CC: 黑玉龙 heiyl@chanjet.com 
 Subject: Re: [weibo_android_sdk] v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权 (#41) 

 应该是这个原因，我用公司注册过的签名就正常授权~ 
 我GitHub有自己写的Demo，如果需要可以参考下~ 

 ------------------ 原始邮件 ------------------ 
 发件人: "woyaowenzi";notifications@github.com; 
 发送时间: 2013年9月12日(星期四) 中午11:09 
 收件人: "mobileresearch/weibo_android_sdk"weibo_android_sdk@noreply.github.com; 

 主题: Re: [weibo_android_sdk] v2.1版的sdk我导入工程导出工程后授权后又再次弹出输入用户名密码再次授权 (#41) 

 我怀疑你的应用没有注册应用程序的包名和签名。
