### ISSUE TITLE
WeiboAuthListener是不是缺少资源文件

### ISSUE THREAD

**Issue by huzc** [mobileresearch/weibo_android_sdk#44]
09-13 15:48:02.422: E/AndroidRuntime(2795): android.content.res.Resources$NotFoundException: String resource ID #0x7f07002c
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.content.res.Resources.getText(Resources.java:230)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.content.res.Resources.getString(Resources.java:314)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.content.Context.getString(Context.java:327)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.weibo.sdk.android.Weibo.KeepAccessToken(Weibo.java:178)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.weibo.sdk.android.Weibo.access$2(Weibo.java:160)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.weibo.sdk.android.Weibo$2.onComplete(Weibo.java:139)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.weibo.sdk.android.WeiboDialog.handleRedirectUrl(WeiboDialog.java:334)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.weibo.sdk.android.WeiboDialog.access$1(WeiboDialog.java:327)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.weibo.sdk.android.WeiboDialog$WeiboWebViewClient.onPageStarted(WeiboDialog.java:299)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:314)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.os.Looper.loop(Looper.java:137)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at android.app.ActivityThread.main(ActivityThread.java:5227)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at java.lang.reflect.Method.invokeNative(Native Method)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at java.lang.reflect.Method.invoke(Method.java:511)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
09-13 15:48:02.422: E/AndroidRuntime(2795):     at dalvik.system.NativeStart.main(Native Method)

这里面少的资源文件是不是需要我们添加？都不给提示的？！

**Comment by huzc** [comment]
反编译你们的demo
   Weibo里面竟然这样写？
   Context localContext = this.ct;
    String str3 = this.ct.getString(2131165228);
    Toast.makeText(localContext, str3, 0).show();
    paramWeiboAuthListener.onComplete(paramBundle);

2131165228这个不能直接指定id，其他程序引用你们的jar R文件根本生成不了这个2131165228

**Comment by woyaowenzi** [comment]
已修正了，重新下载下JAR包试试。
