### ISSUE TITLE
com.weibo.sdk.view.LoginButton 登录按钮控件如何设置APP_KEY？？？

### ISSUE THREAD

**Issue by jy1989** [mobileresearch/weibo_android_sdk#45]
mLoginBt = (LoginButton) findViewById(R.id.login_bt);
  mLoginBt.setCurrentActivity(this);
  mLoginBt.setAuthListener(mLoginListener);

如何设置app key？？？

**Comment by woyaowenzi** [comment]
现在的解决办法是ConstantS里面，替换自己的APP_KEY。
    // 应用的key 请到官方申请正式的appkey替换APP_KEY
    public static final String APP_KEY      = "2045436852";

反编译代码后，现在的LoginButton直接使用了
    mWeiboAuth = Weibo.getInstance(ConstantS.APP_KEY, ConstantS.REDIRECT_URL, ConstantS.SCOPE);
我觉得这是不合理的，应该让用户传进去。

**Comment by woyaowenzi** [comment]
看一下V2.4.0的DEMO，LoginButton 已开源。
