### ISSUE TITLE
WeiboDialog全屏显示问题

### ISSUE THREAD

**Issue by huzc** [mobileresearch/weibo_android_sdk#47]
我这边程序默认是全屏显示的，但是WeiboDialog貌似不是全屏显示的这样的话在调用的时候认证的dialog显示不全界面非常难看，不知道sdk里面是否有全屏显示的设置？

**Comment by huzc** [comment]
或者能不能您在WeiboDialog修改一下单独给我一个新的sdk?(用户体验太差了)邮箱huzc1987@gmail.com

**Comment by mobileresearch** [comment]
可以考虑全屏显示的设置选项。争取下一版实现。谢谢

**Comment by heyixian2008** [comment]
heyixian

发件人： mobileresearch
发送时间： 2013-09-24 13:01
收件人： mobileresearch/weibo_android_sdk
主题： Re: [weibo_android_sdk] WeiboDialog全屏显示问题 (#47)
可以考虑全屏显示的设置选项。争取下一版实现。谢谢
