### ISSUE TITLE
弹出的dialog大小有问题

### ISSUE THREAD

**Issue by xieyiyi** [mobileresearch/weibo_android_sdk#48]
Android版本4.2.2，如果是Nexus 4对话框的大小没有问题
但是如果是其它的16:9屏幕的机型，这个对话框的大小就有问题了：
屏幕键盘将会挡住登录的密码输入框，而这个dialog本来应该充满屏幕除去虚拟键盘后剩下的空间，但是实际上dialog没有充分利用屏幕的显示空间
![device-2013-09-29-131633](https://f.cloud.github.com/assets/5567568/1232539/f7a52d16-28c6-11e3-898d-772634c8cd40.png)
![device-2013-09-29-131704](https://f.cloud.github.com/assets/5567568/1232541/fd8f50ee-28c6-11e3-962a-99e859e3d825.png)

**Comment by mobileresearch** [comment]
@xieyiyi 这个问题已经在V2.4.0里面修正了，你测试一下。
