### ISSUE TITLE
微博sdkDemo 不能注册到微博

### ISSUE THREAD

**Issue by ouyongpeng** [mobileresearch/weibo_android_sdk#49]
替换了APP_KEY 运行，可以OAUTH，但注册到微博时后台显示错误
Failed to find provider info for com.sina.weibo.sdkProvider
WeiboApiImpl  registerApp() failed winfo == null
检测是否支持SDK显示为否的
后台打印supportApi为-1
之后试过直接adb install 微博Demo示例，还是这个状况，请问我是哪里搞错了？（我是用2.3最新版的）

**Comment by mobileresearch** [comment]
你安装的微博版本不对吧？用最新版本的微博客户端试试。
