### ISSUE TITLE
SSO onActivityResult Intent has only "code" in Extra

### ISSUE THREAD

**Issue by TintypeMolly** [mobileresearch/weibo_android_sdk#51]
I'm using this jar to implement authorization through Weibo Android Application. Clicking `com.weibo.sdk.view.LoginButton` DOES SEND `Intent` to Android Weibo Application,
and my `Activity` DOES RECEIVE some kind of `Intent` from Android Weibo Application.
So I called 

```
SsoHandler.authorizeCallBack(requestCode, resultCode, data);
```

in the `onActivityResult(int requestCode, int resultCode, Intent data)`
But this code didn't call `onComplete` function of my `WeiboAuthListener`, and just shows another weibo login dialog which shows up when I call

```
void com.weibo.sdk.android.sso.SsoHandler.authorizeCallBack(int requestCode,
    int resultCode,
    Intent data)
```

So I decompiled the jar file and what's happening.

There, I could find out why.

The `Extra` data of `Intent` got from onActivityResult has only `"code"` as its key.

But this SDK assumes that Android Weibo Application returns perfect access token data like `"access_token"`, `"expires_in"`, and `"refresh_token"`.

So the SDK think that the authorization has failed, thus we must try authorization again not using Android Weibo Application.

I think this needs immediate fix.

I'm using Android Weibo Application version 4.0.1, the most current one.

**Comment by mobileresearch** [comment]
The reason why you can NOT login with SSO is that you Signature of you APP is not correct. Please check it. To solve your problem, you should read the document of [微博Android平台SDK文档V2.3.0.pdf](https://raw.github.com/mobileresearch/weibo_android_sdk/master/%E5%BE%AE%E5%8D%9AAndroid%E5%B9%B3%E5%8F%B0SDK%E6%96%87%E6%A1%A3V2.3.0.pdf) ：**如何注册应用程序的包名和签名**.

**Comment by TintypeMolly** [comment]
I already set package name and app signature at app center.

But, I think your answer does make some point.

I don't think that I provided my `appKey` to weibo sso sdk.

If I directly use `com.weibo.sdk.Weibo` class to authorize,

I provide `appKey` as first argument becuase `getInstance` function looks like

```
public static synchronized Weibo getInstance(String appKey, String redirectUrl, String aScope)
```

Maybe the problem starts from there.

Using `com.weibo.sdk.view.LoginButton`, there is no method that I can provide my app's `appKey`.

Decompiled code shows me that it acts like passing some default app's appKey, not mine.

```
 LoginButton.this.mWeiboAuth = Weibo.getInstance("2045436852", "http://www.sina.com", "email,direct_messages_read,direct_messages_write,friendships_groups_read,friendships_groups_write,statuses_to_me_read,follow_app_official_microblog,invitation_write");
```

And I don't see any way to specify my app key when I'm using `LoginButton` class.

Even the demo acts like this.

Am I missing something with using LoginButton?

Or Is there any way to set appKey?

Or is it just my typing error at the Weibo app center?

I reviewed the values at the Weibo app center,

but I don't see wrong information about app package name and app signature.

T.T

**Comment by TintypeMolly** [comment]
I solved this problem.
`com.weibo.sdk.view.LoginButton` seems like it is not meant to be used for general application.
I manually implemented `MyLoginButton` which acts just same with `LoginButton`
except for `appKey`, `redirectUri`, and it worked well.
I thought `LoginButton` is meant to be used for application developer using weibo oauth api
because it is packed within one jar file, but maybe it wasn't like that.
Maybe it's just for demonstration.
I think it would be very nice if `LoginButton` class can take `appKey`, `redirectUri`, `scope` as user-settable member.
Thank you for helping me, @mobileresearch

**Comment by asfman** [comment]
发现个很严重的问题，我的应用在开发者平台已经上线，但是以前是没有要求填写Android包名 签名这些的，需要编辑重新填写这些，那么我编辑保存后，会不会又要重新审核上线了？

**Comment by mobileresearch** [comment]
@TintypeMolly Sorry for my late response. We have release **V2.4.0**, you can try to use the new version, and we have opened the source for **LoginButton** widget and some **Open API**.

**Comment by mobileresearch** [comment]
@asfman 需要，你联系下联系下平台审核的相关人员，让他们给加急审核一下吧。

**Comment by ziyan** [comment]
有没有办法重用网站的API Key？例如，我们已经有一个通过审核的网站了，主要使用微博提供登录。微博授权用户也有几千了。现在我们需要开发Android应用，可否：
1. 使用网站的API Key
2. 手机通过SSO获取Code
3. 手机把Code发给网站服务器，网站服务器获取Access Token，授权用户登录

如果再注册一个API Key之前已经授权得用户就得再授权一遍。况且手机是否拿到Access Token对我们来说不重要，反正服务器怎么也得验证Code或者Token是否真的有效。

**Comment by woyaowenzi** [comment]
@ziyan 
1：不可以。移动应用和Web应用现在是不能统一的。
2和3：通过SSO不能获取Code，你可以查看Demo，里面有如何获取Code，并获取Token的示例。
请在微博SDK新地址里获取最新版本：`https://github.com/sinaweibosdk`

> 1. 有没有办法重用网站的API Key？
> 2. 手机通过SSO获取Code
> 3. 手机把Code发给网站服务器，网站服务器获取Access Token，授权用户登录
