### ISSUE TITLE
使用sso或者网页方式授权，跳转到登陆界面后取消，再登陆，再取消，这样重复几次崩溃

### ISSUE THREAD

**Issue by jackfengji** [mobileresearch/weibo_android_sdk#52]
无微博客户端情况
10-25 10:24:45.748: E/AndroidRuntime(8441): FATAL EXCEPTION: main
10-25 10:24:45.748: E/AndroidRuntime(8441): java.lang.IllegalArgumentException: View not attached to window manager
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:385)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:287)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.app.Dialog.dismissDialog(Dialog.java:323)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.app.Dialog.dismiss(Dialog.java:306)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at com.weibo.sdk.android.WeiboDialog$WeiboWebViewClient.onPageFinished(SourceFile:315)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:340)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.os.Handler.dispatchMessage(Handler.java:107)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.os.Looper.loop(Looper.java:194)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at android.app.ActivityThread.main(ActivityThread.java:5449)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at java.lang.reflect.Method.invokeNative(Native Method)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at java.lang.reflect.Method.invoke(Method.java:525)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
10-25 10:24:45.748: E/AndroidRuntime(8441):     at dalvik.system.NativeStart.main(Native Method)

**Comment by woyaowenzi** [comment]
最新的V2.4.0版，应该修正该问题了。
