### ISSUE TITLE
WeiboShareSDK.createWeiboAPI传入Application Context时分享crash

### ISSUE THREAD

**Issue by achellies** [mobileresearch/weibo_android_sdk#67]
WeiboShareSDK.createWeiboAPI 输入参考第一个参数类型是context，但在实际发送分享的时候weiboShareSDK中的
  public boolean sendRequest(BaseRequest request)
  {
    return shareWithWeibo((Activity)this.mContext, "com.sina.weibo.sdk.action.ACTION_WEIBO_ACTIVITY", this.mWeiboInfo.packageName, this.mAppKey, data);
  }

发把Context强制转成Activity，从而调用Activity的startActvityForResult方法，

这里WeiboShareSDK.createWeiboAPI的第一个入参应该改为Activity，

**Comment by woyaowenzi** [comment]
说得没错，这是个失误，没有给大家一个详细的提示，直接写activity就好了
