### ISSUE TITLE
获取用户信息报错

### ISSUE THREAD

**Issue by jiasheng-li089** [mobileresearch/weibo_android_sdk#73]
使用Demo来获取用户信息的时候，抛出com.sina.weibo.sdk.exception.WeiboException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate异常。
以下是异常详细信息：
12-30 12:50:02.780: E/com.sina.weibo.sdk.demo.openapi.WBUserAPIActivity(2541): WBUserAPIActivity.java(135) onWeiboException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
12-30 12:50:02.780: W/System.err(2541): org.json.JSONException: Value javax.net.ssl.SSLPeerUnverifiedException of type java.lang.String cannot be converted to JSONObject
12-30 12:50:02.780: W/System.err(2541):     at org.json.JSON.typeMismatch(JSON.java:111)
12-30 12:50:02.780: W/System.err(2541):     at org.json.JSONObject.<init>(JSONObject.java:160)
12-30 12:50:02.780: W/System.err(2541):     at org.json.JSONObject.<init>(JSONObject.java:173)
12-30 12:50:02.780: W/System.err(2541):     at com.sina.weibo.sdk.openapi.models.ErrorInfo.parse(ErrorInfo.java:42)
12-30 12:50:02.780: W/System.err(2541):     at com.sina.weibo.sdk.demo.openapi.WBUserAPIActivity$1.onWeiboException(WBUserAPIActivity.java:136)
12-30 12:50:02.780: W/System.err(2541):     at com.sina.weibo.sdk.net.AsyncWeiboRunner$RequestRunner.onPostExecute(AsyncWeiboRunner.java:137)
12-30 12:50:02.780: W/System.err(2541):     at com.sina.weibo.sdk.net.AsyncWeiboRunner$RequestRunner.onPostExecute(AsyncWeiboRunner.java:1)
12-30 12:50:02.780: W/System.err(2541):     at android.os.AsyncTask.finish(AsyncTask.java:632)
12-30 12:50:02.780: W/System.err(2541):     at android.os.AsyncTask.access$600(AsyncTask.java:177)
12-30 12:50:02.780: W/System.err(2541):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
12-30 12:50:02.780: W/System.err(2541):     at android.os.Handler.dispatchMessage(Handler.java:102)
12-30 12:50:02.780: W/System.err(2541):     at android.os.Looper.loop(Looper.java:135)
12-30 12:50:02.780: W/System.err(2541):     at android.app.ActivityThread.main(ActivityThread.java:5221)
12-30 12:50:02.780: W/System.err(2541):     at java.lang.reflect.Method.invoke(Native Method)
12-30 12:50:02.780: W/System.err(2541):     at java.lang.reflect.Method.invoke(Method.java:372)
12-30 12:50:02.780: W/System.err(2541):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
12-30 12:50:02.780: W/System.err(2541):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Samsu7609** [comment]
我目前也是遇到相同的問題
手機安裝微博版本 5.1.1
請問各位開發者有遇到相同的問題嗎? 及 如何解決?

**Comment by jiasheng-li089** [comment]
他這個版本應該是已經廢棄了的，我去他官網找到另外一個新版本就不會出現在這錯誤了。https://github.com/sinaweibosdk/weibo_android_sdk

**Comment by Samsu7609** [comment]
@ljsalm089 你在授權時候有遇過此問題嗎?
手機安裝微博版本 5.1.1

![screenshot_2015-03-02-16-24-32](https://cloud.githubusercontent.com/assets/6458119/6437594/e66e01b6-c0fb-11e4-8b11-32b5d7de98ec.png)

**Comment by jiasheng-li089** [comment]
沒有，你有沒有換成上面那個url中的那個SDK？

**Comment by Samsu7609** [comment]
@ljsalm089 我已經換成 https://github.com/sinaweibosdk/weibo_android_sdk 這個link 的SDK 
但是有 "網路不給力稍後再試試 C7003"
可以請問你手機上的微博版本嗎?

**Comment by jiasheng-li089** [comment]
5.0.0

**Comment by BatnettWang** [comment]
我也遇到相同的问题   怎么解决呀？求大神指导

**Comment by jiasheng-li089** [comment]
你是指上面错误日志中的问题还是“网络不给力”的那个问题？如果是网络不给力的那个问题，我没有遇到过，如果是错误日志中的那个问题，看看前面的回复。该SDK已经废弃了的，去某浪找最新版的SDK吧。

**Comment by BatnettWang** [comment]
我授权已经成功了，拿到了 AccessToken  ，获取用户信息的报的No peer certificate异常。我的sdk是 5月份的从官网下的，这么快就被放弃了 ？

**Comment by jiasheng-li089** [comment]
我是说这个Repository的sdk被废弃了，我不知道你的sdk是啥情况.
