### ISSUE TITLE
demo绑定完微博直接crash,貌似代码都没写完么

### ISSUE THREAD

**Issue by cacawai** [mobileresearch/weibo_android_sdk#8]
12-24 16:47:15.570: E/AndroidRuntime(17398): java.lang.NullPointerException
12-24 16:47:15.570: E/AndroidRuntime(17398):    at com.weibo.sdk.android.demo.MainActivity$AuthDialogListener.onComplete(MainActivity.java:135)
12-24 16:47:15.570: E/AndroidRuntime(17398):    at com.weibo.sdk.android.Weibo$1.onComplete(Weibo.java:83)
12-24 16:47:15.570: E/AndroidRuntime(17398):    at com.weibo.sdk.android.WeiboDialog.handleRedirectUrl(WeiboDialog.java:238)
12-24 16:47:15.570: E/AndroidRuntime(17398):    at com.weibo.sdk.android.WeiboDialog.access$1(WeiboDialog.java:231)
12-24 16:47:15.570: E/AndroidRuntime(17398):    at com.weibo.sdk.android.WeiboDialog$WeiboWebViewClient.onPageStarted(WeiboDialog.java:206)

**Comment by yushiro** [comment]
MainActivity中未定义apiBtn对象， 导致授权成功后apiBtn.setVisibility(View.VISIBLE);这里产生null异常。

**Comment by iweey** [comment]
官方还是把这个bug修复了吧 新人真以为怎么了

**Comment by gen30** [comment]
这么低级的错误，写完没测试一下吗？难道新浪没给程序员发工资？

**Comment by liumingkong** [comment]
楼上，这种事情怎么能直说...

**Comment by mobileresearch** [comment]
@cacawai @yushiro @iweey @gen30 @liumingkong 你们太幽默了。感谢您提供的宝贵意见，该问题已做修正，欢迎体验V2.4.0的代码及文档，再次期望您能提出宝贵的意见。
